# ----
# Site

title: Wiki Robotech Nancy
domain: RobotechNancy.github.io
url: https://RobotechNancy.github.io/Wiki

google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Wiki du pôle informatique de Robotech Nancy
author:
  name: MrSpaar
  email:
  twitter: MrSpaar
social:
  name: Wiki Robotech Nancy
  links:
    - https://github.com/RobotechNancy
    - https://robotech.polytech-nancy.univ-lorraine.fr/

# -----
# Build

timezone: Europe/Paris

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
