# ----
# Site

title: Wiki Robotech Nancy
domain: robotechnancy.github.io
url: https://robotechnancy.github.io/
description: Bienvenue sur le wiki de Robotech, ici se trouvent des ressources pour le développement embarqué.
timezone: Europe/Paris

# -----
# Build

plugins:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
include:
  - _layouts

sass:
  style: compressed
  sass_dir: css

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
